#SPDX-License-Identifier: MIT-0
---
# tasks file for role/docker
#
# This file can install and run the Docker on ubuntu machine

- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  become: yes

- name: Update system
  apt:
    name: "*"
    state: latest

- name: Install docker.io
  apt:
    name: docker.io
    state: latest

- name: Add user to dockergroup
  user:
    name: "{{ item }}" 
    groups: docker
    append: true
      # sudo usermod -aG docker ubuntu here we use append  
  loop: "{{ docker_users }}"


- name: regsiter the docker version to the variable
  command: docker --version
  register: docker_version

- name: show Docker version  
  debug:
    msg: "{{ docker_version }}"
