- name: Show secrets
  hosts: server
  become: yes

  vars_files:
    - secret.yml
  tasks:
    - name: show password
      debug:
        msg: "Password is {{ password }}"
      no_log: true # to stop display the output on screen
    - name: show APIkey
      debug:
        msg: "APIkey is {{ apikey }}"
